### ISSUE TITLE
System sends notification of Accepted donation

### ISSUE THREAD

**Issue by francischeung** [SeattleGiveCamp/SGC2017_OSL#65]
After user taps "Accept" button on Pickup Details page, system sends email/sms message to user.

Message should contain sufficient information to pickup donation.

**Comment by francischeung** [comment]
System should also send email/sms to donor informing them about the recipient who has accepted.

**Comment by halfnibble** [comment]
Email would be free using Sendgrid. Also looking into App notifications using Azure.

**Comment by halfnibble** [comment]
**Create email notification in Accept Donation API to send Donor an email when a recipient user accepts a donation.**
